apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flask-gql-deploy
  name: flask-gql
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask-gql-deploy
  type: NodePort
status:
  loadBalancer: {}
